apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracking-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ethan510010/tracking_test.git
    path: tracking-test
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated: null
