---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-root-password
  namespace: default
spec:
  encryptedData:
    password: AgBQMzXCDLXzuJDoK8CS+2cm7xH2LwDE4Ks2I9S8RzacPkc64vnaGXFGmZMkI1OsaSfthornfqX6Hjr5upGlv0UqT5u0KzmHKJjxyLN8pOWYEVbf+QeYoYMW4mHKzTrfKg36io/9hagPgkEV0TcYuJ0oYzo9yuEszOojL+ARhtsFJJdC5SQD9yw1RTaNmjNVJoc1gqGMqRU4oC+cT5ghc/2YL0IKlEdLVwEuwEACehrGGbOqolgTgWcIc67XfRc03sfP2y1EzkaTAo/JjN9vXeSApbYUTfQbw0byubPCdKIjWKIglwlrpZdSrZ75MWBFoDA7O+4Vh5cWEP2yCEJIsT0U23wIOhYX5IUJxGzSoekyoOPH7Advr7yKFONzwHwM7GOMgC+lEeztc+maG874M1CL9XNFuM9FKJVb+0AnXsY42g1kJFKDooxZdoJTlDngyAt42VD9ST+exTtB3GJugpSU0dwGYq6iRmHad5ofHCqWftHyYRzxwZ+tDKmHdkJuX/mgsIt7y7ArA1Qw7VaeSQ3S6HU36K1W8Xh6ZMXWeT+/XT0WtUOJyJCdYD8vz9sA5NtFb949JTwEngJ+7jg7R+fECUPdXnOBHq9+BvwAakTUwPWXn/NsbSYQNVrWohqlogYt4ievE/DLl0EVkHi4FI2D8J6wrolu4wsL1z2R8FbdI2Zt73L5wmS0UeE3zBfxnD0LVhtgrob+xO0=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-root-password
      namespace: default
    type: Opaque
