---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-root-password
  namespace: default
spec:
  encryptedData:
    password: AgBwv3HEazDmaskjMb6oMBGnQLqdgug/3ejVACh7Gz//A8F7HfdUchWWe5VP2nhoUpObE8QxF7a5/wsdqrC5URIAvczhEMIsVNUjBrWuP/O9EJ2IP16S5ytH5mWyF3y9D6dmxyD4/gtu/6PxRbkGaQHwzus2AH2WLh6clC5i/sDKrqx/KBdq4iLCUt1Tkn7LbDgVFYVlc7C5guI2p05+xxljgz/jWFPkHvtgpOWGmWOy/kjEHJNpJUtbJUU7KyZxDX66xuuYFygS7utD5VATgjKkSAHdmnKJagLkn0J3HPSzVMVvdlwVjyAKgPMhq6QwWTQFXt1suMShKEdmaItl41Rp5+BxONKLhgxaVV2JsAm8GzqD7zmgBKbdfJrlS5CAU3Ck/PgxxTsYlxvK5Pm8aJ329DzLcSDa6U0cIRC8fJb+IYzifFHKfNoTOUxw5S4pheNMb5tz+jfObplEscupnUFh+SFdmpQ54gdl4WugpyL/sywdzqyC+lXoNliWTovBtAIXAPHaDmCJBXjc6NmtcatWEZr6OfXW9xgFecSJaWLrGCuq+4Xwt5dgz34mRYOkak29Z5pvJLDHo23Zfbjri7AEF6eWdFAetFBmI910QJfUE/v7T6lrdhki8dyViqbCdxr9rILCcPxWxrBeQWr2s4Pf7OYZJ6AeULquYIiBc99SU1+A/5kbgPwFsM+K1gZukfKY6ZvpWgZOljE=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-root-password
      namespace: default
    type: Opaque
