---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-root-password
  namespace: default
spec:
  encryptedData:
    password: AgByq3+SwoNEQwN7ZLyFXdNCy7M+SJ1R/7iA7MSHZ74supku4fBxN1rLhJ1/VSyV1qgIwUHfyexzajUwC6GKNiCE95DNCu/h6lyvvfVWS4aj/GWK6Dmf2JwkffI+zvXxBfMHJUG7yugvHBTM8nXGddhVp+AY+CS+B9ftRBe8B/6RyWopgZ/r6bfMPIGjYg7Dr5RFcUdRVmbVSKlT2xvd5egs+wvF1QEU477ma21+4I2eyNEjBJHMJ8lUkKjU9EMHO5fVwdBHNytE5sntkpIlg6hsv8Ri6FGyKBnbeFI734q/8AUmsgazlq8kSv0KJBJ1JBDWL1/vwnHhjYuQDaLjETXwbD+ZLD+zTgeFQKqKG4wufot52i0T93+JrIToo4aczUs/50vGqU7QEyJ3S4MuvswA+5hisW+7aWJxPMorgHP//TaVdnQ0wv41fARnXKT8qeewasKTM98/cs2Z6Ir6AsUBZ9hXU958HAxJNFRDYb8vGNS7ytRNHi6Tw6jyxNg6Neet4WKURY/qh1ujjyVZk+nmZCwS8XlKb/56pna1e9nMIJXB8iPHjUPVp9EDdrfqamjP1ogCeJpAM8+FiV3K04BywQpj4ydV8WuI+WzmsPFbZxCLgBSB2I1yVOaWm3NbkHcUxU9hj6CYr/GzolGit93wUoHgmHAGFE5tpcRxq27+uvBdkYMkmnWUbIk0/NI8nYAbLTs+IOlbnQQ=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-root-password
      namespace: default
    type: Opaque
