apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webSrv.service.name }}
spec:
  type: {{ .Values.webSrv.service.type }}
  ports:
    - port: {{ .Values.webSrv.service.port }}
      targetPort: {{ .Values.webSrv.container.port }}
  selector:
    app: {{ .Values.webSrv.deployment.label }}
