apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.webSrv.configMap.name }}
data:
  api.env: |
    DB_HOST={{ .Values.db.statefulSet.name }}
    DB_USER=root
    REDIS_HOST={{ .Values.redis.statefulSet.name }}
    REDIS_PORT={{ .Values.redis.container.port }}
